import pandas as pd

words = {
    "the food": "das Essen",
    "the meal": "die Mahlzeit",
    "the breakfast": "das Frühstück",
    "the lunch": "das Mittagessen",
    "the dinner": "das Abendessen",
    "the snack": "der Snack",
    "the bread": "das Brot",
    "the roll": "das Brötchen",
    "the butter": "die Butter",
    "the cheese": "der Käse",
    "the sausage": "die Wurst",
    "the ham": "der Schinken",
    "the egg": "das Ei",
    "the soup": "die Suppe",
    "the salad": "der Salat",
    "the potato": "die Kartoffel",
    "the rice": "der Reis",
    "the pasta": "die Nudeln",
    "the vegetable": "das Gemüse",
    "the fruit": "das Obst",
    "the apple": "der Apfel",
    "the banana": "die Banane",
    "the orange": "die Orange",
    "the tomato": "die Tomate",
    "the cucumber": "die Gurke",
    "the carrot": "die Karotte",
    "the onion": "die Zwiebel",
    "the garlic": "der Knoblauch",
    "the meat": "das Fleisch",
    "the fish": "der Fisch",
    "the chicken": "das Hähnchen",
    "the beef": "das Rindfleisch",
    "the pork": "das Schweinefleisch",
    "the dessert": "der Nachtisch",
    "the cake": "der Kuchen",
    "the chocolate": "die Schokolade",
    "the marmalade": "die Marmelade",
    "the water": "das Wasser",
    "the coffee": "der Kaffee",
    "the tea": "der Tee",
    "the milk": "die Milch",
    "the juice": "der Saft",
    "the lemonade": "die Limonade",
    "the beer": "das Bier",
    "the wine": "der Wein",
    "the salt": "das Salz",
    "the pepper": "der Pfeffer",
    "the sugar": "der Zucker",
    "the flour": "das Mehl",
    "the oil": "das Öl",
    "the vinegar": "der Essig",
    "the sauce": "die Soße",
    "the mustard": "der Senf",
    "the ketchup": "der Ketchup",
    "the honey": "der Honig",
    "the jam": "die Konfitüre",
    "the cream": "die Sahne",
    "the yogurt": "der Joghurt",
    "the curd": "der Quark",
    "the cereal": "das Müsli",
    "the oatmeal": "die Haferflocken",
    "the strawberry": "die Erdbeere",
    "the raspberry": "die Himbeere",
    "the blueberry": "die Heidelbeere",
    "the grape": "die Traube",
    "the pear": "die Birne",
    "the peach": "der Pfirsich",
    "the lemon": "die Zitrone",
    "the pepper vegetable": "die Paprika",
    "the lettuce": "der Kopfsalat",
    "the cabbage": "der Kohl",
    "the cauliflower": "der Blumenkohl",
    "the broccoli": "der Brokkoli",
    "the mushroom": "der Pilz",
    "the bean": "die Bohne",
    "the pea": "die Erbse",
    "the lentil": "die Linse",
    "the corn": "der Mais",
    "the pumpkin": "der Kürbis",
    "the cheese slice": "die Käsescheibe",
    "the toast": "der Toast",
    "the sandwich": "das belegte Brot",
    "the pizza": "die Pizza",
    "the burger": "der Burger",
    "the fries": "die Pommes",
    "the dumpling": "der Kloß",
    "the pancake": "der Pfannkuchen",
    "the ice cream": "das Eis",
    "the cookie": "der Keks",
    "the candy": "die Süßigkeit",
    "the pudding": "der Pudding",
    "the recipe": "das Rezept",
    "the ingredient": "die Zutat",
    "the portion": "die Portion",
    "the menu": "die Speisekarte",
    "the dish": "das Gericht",
    "the appetizer": "die Vorspeise",
    "the main course": "das Hauptgericht",
    "the side dish": "die Beilage",
    "the drink": "das Getränk"
}

df = pd.DataFrame.from_dict(
    words,
    orient="index",
    columns=["German"]
)

df.index.name = "English"

df.to_csv("dict_Nomen_Essen.csv")
