import pandas as pd

words = {
    "the vacation": "der Urlaub",
    "the trip": "die Reise",
    "the journey": "die Fahrt",
    "the destination": "das Reiseziel",
    "the country": "das Land",
    "the island": "die Insel",
    "the beach": "der Strand",
    "the sea": "das Meer",
    "the lake": "der See",
    "the mountain": "der Berg",
    "the hotel": "das Hotel",
    "the room": "das Zimmer",
    "the reception": "die Rezeption",
    "the reservation": "die Reservierung",
    "the booking": "die Buchung",
    "the passport": "der Reisepass",
    "the identity card": "der Personalausweis",
    "the ticket": "das Ticket",
    "the flight": "der Flug",
    "the airport": "der Flughafen",
    "the airplane": "das Flugzeug",
    "the train station": "der Bahnhof",
    "the suitcase": "der Koffer",
    "the backpack": "der Rucksack",
    "the bag": "die Tasche",
    "the map": "die Karte",
    "the guidebook": "der Reiseführer",
    "the camera": "die Kamera",
    "the sunscreen": "die Sonnencreme",
    "the sunglasses": "die Sonnenbrille",
    "the towel": "das Handtuch",
    "the swimsuit": "der Badeanzug",
    "the swimming trunks": "die Badehose",
    "the excursion": "der Ausflug",
    "the sight": "die Sehenswürdigkeit",
    "the tour": "die Tour",
    "the restaurant": "das Restaurant",
    "the bill": "die Rechnung",
    "the souvenir": "das Souvenir",
    "the weather": "das Wetter",
    "the travel agency": "das Reisebüro",
    "the brochure": "die Broschüre",
    "the itinerary": "der Reiseplan",
    "the departure": "die Abreise",
    "the arrival": "die Ankunft",
    "the check-in": "der Check-in",
    "the check-out": "der Check-out",
    "the boarding pass": "die Bordkarte",
    "the gate": "das Gate",
    "the terminal": "das Terminal",
    "the baggage": "das Gepäck",
    "the hand luggage": "das Handgepäck",
    "the luggage tag": "der Gepäckanhänger",
    "the baggage claim": "die Gepäckausgabe",
    "the customs": "der Zoll",
    "the border": "die Grenze",
    "the visa": "das Visum",
    "the insurance": "die Versicherung",
    "the travel insurance": "die Reiseversicherung",
    "the vaccination": "die Impfung",
    "the pharmacy": "die Apotheke",
    "the first-aid kit": "die Reiseapotheke",
    "the guide": "der Reiseführer",
    "the tourist": "der Tourist",
    "the group": "die Gruppe",
    "the excursion bus": "der Reisebus",
    "the rental car": "der Mietwagen",
    "the ferry": "die Fähre",
    "the ship": "das Schiff",
    "the cruise": "die Kreuzfahrt",
    "the campsite": "der Campingplatz",
    "the tent": "das Zelt",
    "the sleeping bag": "der Schlafsack",
    "the cabin": "die Hütte",
    "the apartment": "die Ferienwohnung",
    "the hostel": "die Jugendherberge",
    "the guesthouse": "die Pension",
    "the pool": "der Pool",
    "the beach chair": "der Strandkorb",
    "the umbrella": "der Sonnenschirm",
    "the flip-flop": "der Flipflop",
    "the hat": "der Hut",
    "the swimsuit top": "das Bikinioberteil",
    "the diving mask": "die Tauchmaske",
    "the snorkel": "der Schnorchel",
    "the hiking trail": "der Wanderweg",
    "the viewpoint": "der Aussichtspunkt",
    "the postcard": "die Postkarte",
    "the stamp": "die Briefmarke",
    "the foreign currency": "die Fremdwährung",
    "the exchange rate": "der Wechselkurs",
    "the cash": "das Bargeld",
    "the credit card": "die Kreditkarte",
    "the wallet": "der Geldbeutel",
    "the language": "die Sprache",
    "the phrasebook": "das Wörterbuch",
    "the culture": "die Kultur",
    "the museum": "das Museum",
    "the old town": "die Altstadt",
    "the memory": "die Erinnerung"
}

df = pd.DataFrame.from_dict(
    words,
    orient="index",
    columns=["German"]
)

df.index.name = "English"

df.to_csv("dict_Nomen_Urlaub.csv")
