import pandas as pd

words = {
    'the media': 'die Medien',
    'the newspaper': 'die Zeitung',
    'the magazine': 'die Zeitschrift',
    'the article': 'der Artikel',
    'the news': 'die Nachrichten',
    'the website': 'die Webseite',
    'the podcast': 'der Podcast',
    'the video': 'das Video',
    'the channel': 'der Kanal',
    'the post': 'der Beitrag',
    'the comment': 'der Kommentar',
    'the photo': 'das Foto',
    'the headline': 'die Überschrift',
    'the report': 'der Bericht',
    'the interview': 'das Interview',
    'the advertisement': 'die Werbung',
    'the source': 'die Quelle',
    'the screen': 'der Bildschirm',
    'the app': 'die App',
    'the profile': 'das Profil',
    'the television': 'das Fernsehen',
    'the radio': 'das Radio',
    'the broadcast': 'die Sendung',
    'the program': 'das Programm',
    'the series': 'die Serie',
    'the episode': 'die Folge',
    'the documentary': 'die Dokumentation',
    'the film review': 'die Filmkritik',
    'the livestream': 'der Livestream',
    'the stream': 'der Stream',
    'the platform': 'die Plattform',
    'the account': 'das Konto',
    'the username': 'der Benutzername',
    'the password': 'das Passwort',
    'the login': 'die Anmeldung',
    'the message': 'die Nachricht',
    'the chat': 'der Chat',
    'the group chat': 'der Gruppenchat',
    'the notification': 'die Benachrichtigung',
    'the feed': 'der Feed',
    'the timeline': 'die Chronik',
    'the story': 'die Story',
    'the reel': 'das Reel',
    'the clip': 'der Clip',
    'the link': 'der Link',
    'the download': 'der Download',
    'the upload': 'der Upload',
    'the attachment': 'der Anhang',
    'the file': 'die Datei',
    'the image': 'das Bild',
    'the graphic': 'die Grafik',
    'the audio': 'die Audiodatei',
    'the recording': 'die Aufnahme',
    'the microphone': 'das Mikrofon',
    'the speaker': 'der Lautsprecher',
    'the camera lens': 'das Objektiv',
    'the editor': 'der Redakteur',
    'the editor female': 'die Redakteurin',
    'the journalist': 'der Journalist',
    'the journalist female': 'die Journalistin',
    'the reporter': 'der Reporter',
    'the presenter': 'der Moderator',
    'the presenter female': 'die Moderatorin',
    'the audience': 'das Publikum',
    'the viewer': 'der Zuschauer',
    'the viewer female': 'die Zuschauerin',
    'the reader': 'der Leser',
    'the reader female': 'die Leserin',
    'the subscriber': 'der Abonnent',
    'the subscription': 'das Abonnement',
    'the follower': 'der Follower',
    'the like': 'das Like',
    'the share': 'das Teilen',
    'the hashtag': 'der Hashtag',
    'the trend': 'der Trend',
    'the algorithm': 'der Algorithmus',
    'the privacy': 'die Privatsphäre',
    'the data protection': 'der Datenschutz',
    'the copyright': 'das Urheberrecht',
    'the license': 'die Lizenz',
    'the archive': 'das Archiv',
    'the search': 'die Suche',
    'the search engine': 'die Suchmaschine',
    'the result': 'das Ergebnis',
    'the rating': 'die Bewertung',
    'the recommendation': 'die Empfehlung',
    'the newsletter': 'der Newsletter',
    'the press': 'die Presse',
    'the press release': 'die Pressemitteilung',
    'the cover page': 'die Titelseite',
    'the column': 'die Kolumne',
    'the editorial': 'der Leitartikel',
    'the fact check': 'der Faktencheck',
    'the rumor': 'das Gerücht',
    'the correction': 'die Korrektur',
    'the censorship': 'die Zensur',
    'the public': 'die Öffentlichkeit',
    'the target group': 'die Zielgruppe',
    'the campaign': 'die Kampagne',
    'the poster': 'das Plakat'
}

df = pd.DataFrame.from_dict(
    words,
    orient="index",
    columns=["German"]
)

df.index.name = "English"

df.to_csv("../csv-files/dict_Nomen_Medien.csv")
