import pandas as pd

words = {
    "the family": "die Familie",
    "the mother": "die Mutter",
    "the father": "der Vater",
    "the parent": "der Elternteil",
    "the parents": "die Eltern",
    "the child": "das Kind",
    "the daughter": "die Tochter",
    "the son": "der Sohn",
    "the sister": "die Schwester",
    "the brother": "der Bruder",
    "the sibling": "das Geschwister",
    "the grandmother": "die Großmutter",
    "the grandfather": "der Großvater",
    "the grandparents": "die Großeltern",
    "the aunt": "die Tante",
    "the uncle": "der Onkel",
    "the cousin": "der Cousin",
    "the niece": "die Nichte",
    "the nephew": "der Neffe",
    "the wife": "die Ehefrau",
    "the husband": "der Ehemann",
    "the partner": "der Partner",
    "the marriage": "die Ehe",
    "the wedding": "die Hochzeit",
    "the baby": "das Baby",
    "the toddler": "das Kleinkind",
    "the teenager": "der Jugendliche",
    "the adult": "der Erwachsene",
    "the relative": "der Verwandte",
    "the relationship": "die Beziehung",
    "the household": "der Haushalt",
    "the birthday": "der Geburtstag",
    "the celebration": "die Feier",
    "the visit": "der Besuch",
    "the childhood": "die Kindheit",
    "the name": "der Name",
    "the age": "das Alter",
    "the home": "das Zuhause",
    "the pet": "das Haustier",
    "the generation": "die Generation",
    "the grandchild": "das Enkelkind",
    "the granddaughter": "die Enkelin",
    "the grandson": "der Enkel",
    "the great-grandmother": "die Urgroßmutter",
    "the great-grandfather": "der Urgroßvater",
    "the stepmother": "die Stiefmutter",
    "the stepfather": "der Stiefvater",
    "the stepchild": "das Stiefkind",
    "the stepsister": "die Stiefschwester",
    "the stepbrother": "der Stiefbruder",
    "the mother-in-law": "die Schwiegermutter",
    "the father-in-law": "der Schwiegervater",
    "the daughter-in-law": "die Schwiegertochter",
    "the son-in-law": "der Schwiegersohn",
    "the sister-in-law": "die Schwägerin",
    "the brother-in-law": "der Schwager",
    "the godmother": "die Patin",
    "the godfather": "der Pate",
    "the guardian": "der Vormund",
    "the ancestor": "der Vorfahr",
    "the descendant": "der Nachkomme",
    "the family tree": "der Stammbaum",
    "the surname": "der Nachname",
    "the first name": "der Vorname",
    "the nickname": "der Spitzname",
    "the address": "die Adresse",
    "the phone number": "die Telefonnummer",
    "the household member": "das Haushaltsmitglied",
    "the roommate": "der Mitbewohner",
    "the neighbor": "der Nachbar",
    "the friend": "der Freund",
    "the friendship": "die Freundschaft",
    "the love": "die Liebe",
    "the engagement": "die Verlobung",
    "the divorce": "die Scheidung",
    "the separation": "die Trennung",
    "the birth": "die Geburt",
    "the pregnancy": "die Schwangerschaft",
    "the adoption": "die Adoption",
    "the custody": "das Sorgerecht",
    "the upbringing": "die Erziehung",
    "the daycare": "die Kita",
    "the kindergarten": "der Kindergarten",
    "the schoolchild": "das Schulkind",
    "the family doctor": "der Hausarzt",
    "the emergency contact": "der Notfallkontakt",
    "the family celebration": "das Familienfest",
    "the anniversary": "der Jahrestag",
    "the invitation": "die Einladung",
    "the gift": "das Geschenk",
    "the photo album": "das Fotoalbum",
    "the memory": "die Erinnerung",
    "the tradition": "die Tradition",
    "the argument": "der Streit",
    "the reconciliation": "die Versöhnung",
    "the support": "die Unterstützung",
    "the care": "die Pflege",
    "the inheritance": "das Erbe",
    "the will": "das Testament",
    "the funeral": "die Beerdigung"
}

df = pd.DataFrame.from_dict(
    words,
    orient="index",
    columns=["German"]
)

df.index.name = "English"

df.to_csv("../csv-files/dict_Nomen_Familie.csv")
