import pandas as pd

words = {
    'the authority': 'die Behörde',
    'the office': 'das Amt',
    'the citizen': 'der Bürger',
    'the form': 'das Formular',
    'the application': 'der Antrag',
    'the document': 'das Dokument',
    'the passport': 'der Reisepass',
    'the identity card': 'der Personalausweis',
    'the residence permit': 'die Aufenthaltserlaubnis',
    'the registration': 'die Anmeldung',
    'the appointment': 'der Termin',
    'the counter': 'der Schalter',
    'the number': 'die Nummer',
    'the signature': 'die Unterschrift',
    'the certificate': 'die Bescheinigung',
    'the copy': 'die Kopie',
    'the fee': 'die Gebühr',
    'the deadline': 'die Frist',
    'the notice': 'der Bescheid',
    'the tax office': 'das Finanzamt',
    'the city hall': 'das Rathaus',
    'the town hall': 'das Bürgeramt',
    'the registry office': 'das Standesamt',
    'the immigration office': 'die Ausländerbehörde',
    'the employment agency': 'die Arbeitsagentur',
    'the job center': 'das Jobcenter',
    'the health department': 'das Gesundheitsamt',
    'the social welfare office': 'das Sozialamt',
    'the youth welfare office': 'das Jugendamt',
    'the vehicle registration office': 'die Zulassungsstelle',
    'the residents registration office': 'das Einwohnermeldeamt',
    'the district office': 'das Bezirksamt',
    'the court': 'das Gericht',
    'the police': 'die Polizei',
    'the fire department': 'die Feuerwehr',
    'the embassy': 'die Botschaft',
    'the consulate': 'das Konsulat',
    'the waiting room': 'das Wartezimmer',
    'the waiting number': 'die Wartenummer',
    'the queue': 'die Warteschlange',
    'the opening hours': 'die Öffnungszeiten',
    'the contact person': 'der Ansprechpartner',
    'the contact person female': 'die Ansprechpartnerin',
    'the clerk': 'der Sachbearbeiter',
    'the clerk female': 'die Sachbearbeiterin',
    'the file': 'die Akte',
    'the case': 'der Fall',
    'the proof': 'der Nachweis',
    'the confirmation': 'die Bestätigung',
    'the approval': 'die Genehmigung',
    'the permission': 'die Erlaubnis',
    'the rejection': 'die Ablehnung',
    'the objection': 'der Widerspruch',
    'the appeal': 'die Beschwerde',
    'the decision': 'die Entscheidung',
    'the regulation': 'die Vorschrift',
    'the law': 'das Gesetz',
    'the rule': 'die Regel',
    'the requirement': 'die Voraussetzung',
    'the obligation': 'die Pflicht',
    'the right': 'das Recht',
    'the responsibility': 'die Zuständigkeit',
    'the process': 'das Verfahren',
    'the processing': 'die Bearbeitung',
    'the processing time': 'die Bearbeitungszeit',
    'the waiting time': 'die Wartezeit',
    'the validity': 'die Gültigkeit',
    'the expiration date': 'das Ablaufdatum',
    'the extension': 'die Verlängerung',
    'the renewal': 'die Erneuerung',
    'the replacement': 'der Ersatz',
    'the loss': 'der Verlust',
    'the birth certificate': 'die Geburtsurkunde',
    'the marriage certificate': 'die Heiratsurkunde',
    'the police clearance certificate': 'das Führungszeugnis',
    'the registration certificate': 'die Meldebescheinigung',
    'the tax identification number': 'die Steueridentifikationsnummer',
    'the social security number': 'die Sozialversicherungsnummer',
    'the health insurance card': 'die Gesundheitskarte',
    'the visa': 'das Visum',
    'the work permit': 'die Arbeitserlaubnis',
    'the certificate of good conduct': 'das polizeiliche Führungszeugnis',
    'the original': 'das Original',
    'the certified copy': 'die beglaubigte Kopie',
    'the translation': 'die Übersetzung',
    'the certification': 'die Beglaubigung',
    'the stamp': 'der Stempel',
    'the seal': 'das Siegel',
    'the envelope': 'der Umschlag',
    'the letter': 'der Brief',
    'the email': 'die E-Mail',
    'the phone number': 'die Telefonnummer',
    'the address': 'die Adresse',
    'the place of residence': 'der Wohnort',
    'the change of address': 'die Adressänderung',
    'the family status': 'der Familienstand',
    'the nationality': 'die Staatsangehörigkeit',
    'the date of birth': 'das Geburtsdatum',
    'the place of birth': 'der Geburtsort',
    'the passport photo': 'das Passfoto'
}

df = pd.DataFrame.from_dict(
    words,
    orient="index",
    columns=["German"]
)

df.index.name = "English"

df.to_csv("../csv-files/dict_Nomen_Behoerden.csv")
