import pandas as pd

words = {
    'the traffic': 'der Verkehr',
    'the street': 'die Straße',
    'the car': 'das Auto',
    'the bus': 'der Bus',
    'the train': 'der Zug',
    'the tram': 'die Straßenbahn',
    'the subway': 'die U-Bahn',
    'the bicycle': 'das Fahrrad',
    'the taxi': 'das Taxi',
    'the ticket': 'die Fahrkarte',
    'the station': 'der Bahnhof',
    'the stop': 'die Haltestelle',
    'the platform': 'der Bahnsteig',
    'the timetable': 'der Fahrplan',
    'the route': 'die Strecke',
    'the delay': 'die Verspätung',
    'the accident': 'der Unfall',
    'the traffic jam': 'der Stau',
    'the parking space': 'der Parkplatz',
    'the license': 'der Führerschein',
    'the vehicle': 'das Fahrzeug',
    'the motorcycle': 'das Motorrad',
    'the scooter': 'der Roller',
    'the truck': 'der Lastwagen',
    'the van': 'der Lieferwagen',
    'the ambulance': 'der Krankenwagen',
    'the police car': 'das Polizeiauto',
    'the ferry': 'die Fähre',
    'the airplane': 'das Flugzeug',
    'the airport': 'der Flughafen',
    'the terminal': 'das Terminal',
    'the gate': 'das Gate',
    'the departure': 'die Abfahrt',
    'the arrival': 'die Ankunft',
    'the departure time': 'die Abfahrtszeit',
    'the arrival time': 'die Ankunftszeit',
    'the connection': 'die Verbindung',
    'the transfer': 'der Umstieg',
    'the passenger': 'der Fahrgast',
    'the driver': 'der Fahrer',
    'the driver female': 'die Fahrerin',
    'the conductor': 'der Schaffner',
    'the conductor female': 'die Schaffnerin',
    'the ticket machine': 'der Fahrkartenautomat',
    'the ticket office': 'der Fahrkartenschalter',
    'the monthly ticket': 'die Monatskarte',
    'the day ticket': 'die Tageskarte',
    'the single ticket': 'die Einzelfahrkarte',
    'the seat': 'der Sitzplatz',
    'the reservation': 'die Reservierung',
    'the luggage': 'das Gepäck',
    'the suitcase': 'der Koffer',
    'the backpack': 'der Rucksack',
    'the bicycle lane': 'der Fahrradweg',
    'the sidewalk': 'der Gehweg',
    'the crosswalk': 'der Zebrastreifen',
    'the intersection': 'die Kreuzung',
    'the roundabout': 'der Kreisverkehr',
    'the traffic light': 'die Ampel',
    'the traffic sign': 'das Verkehrsschild',
    'the speed limit': 'die Geschwindigkeitsbegrenzung',
    'the highway': 'die Autobahn',
    'the country road': 'die Landstraße',
    'the lane': 'die Spur',
    'the exit': 'die Ausfahrt',
    'the entrance': 'die Einfahrt',
    'the bridge': 'die Brücke',
    'the tunnel': 'der Tunnel',
    'the construction site': 'die Baustelle',
    'the detour': 'die Umleitung',
    'the breakdown': 'die Panne',
    'the repair': 'die Reparatur',
    'the gas station': 'die Tankstelle',
    'the fuel': 'der Kraftstoff',
    'the gasoline': 'das Benzin',
    'the diesel': 'der Diesel',
    'the charging station': 'die Ladestation',
    'the parking garage': 'das Parkhaus',
    'the parking meter': 'die Parkuhr',
    'the parking ticket': 'der Parkschein',
    'the fine': 'das Bußgeld',
    'the speed camera': 'der Blitzer',
    'the insurance': 'die Versicherung',
    'the registration': 'die Zulassung',
    'the license plate': 'das Kennzeichen',
    'the vehicle document': 'der Fahrzeugschein',
    'the inspection': 'die Hauptuntersuchung',
    'the steering wheel': 'das Lenkrad',
    'the brake': 'die Bremse',
    'the tire': 'der Reifen',
    'the engine': 'der Motor',
    'the mirror': 'der Spiegel',
    'the seat belt': 'der Sicherheitsgurt',
    'the helmet': 'der Helm',
    'the map': 'die Karte',
    'the navigation system': 'das Navigationsgerät',
    'the distance': 'die Entfernung',
    'the direction': 'die Richtung',
    'the destination': 'das Ziel',
    'the journey': 'die Fahrt'
}

df = pd.DataFrame.from_dict(
    words,
    orient="index",
    columns=["German"]
)

df.index.name = "English"

df.to_csv("../csv-files/dict_Nomen_Verkehr.csv")
