import pandas as pd

words = {
    'the technology': 'die Technik',
    'the device': 'das Gerät',
    'the computer': 'der Computer',
    'the laptop': 'der Laptop',
    'the phone': 'das Handy',
    'the tablet': 'das Tablet',
    'the screen': 'der Bildschirm',
    'the keyboard': 'die Tastatur',
    'the mouse': 'die Maus',
    'the cable': 'das Kabel',
    'the battery': 'der Akku',
    'the charger': 'das Ladegerät',
    'the software': 'die Software',
    'the program': 'das Programm',
    'the file': 'die Datei',
    'the folder': 'der Ordner',
    'the password': 'das Passwort',
    'the network': 'das Netzwerk',
    'the printer': 'der Drucker',
    'the update': 'das Update',
    'the smartphone': 'das Smartphone',
    'the monitor': 'der Monitor',
    'the touch screen': 'der Touchscreen',
    'the speaker': 'der Lautsprecher',
    'the headphone': 'der Kopfhörer',
    'the microphone': 'das Mikrofon',
    'the webcam': 'die Webcam',
    'the router': 'der Router',
    'the server': 'der Server',
    'the cloud': 'die Cloud',
    'the database': 'die Datenbank',
    'the website': 'die Webseite',
    'the browser': 'der Browser',
    'the search engine': 'die Suchmaschine',
    'the email': 'die E-Mail',
    'the message': 'die Nachricht',
    'the attachment': 'der Anhang',
    'the link': 'der Link',
    'the download': 'der Download',
    'the upload': 'der Upload',
    'the backup': 'die Sicherungskopie',
    'the memory': 'der Speicher',
    'the hard drive': 'die Festplatte',
    'the processor': 'der Prozessor',
    'the chip': 'der Chip',
    'the circuit board': 'die Platine',
    'the plug': 'der Stecker',
    'the socket': 'die Steckdose',
    'the adapter': 'der Adapter',
    'the power supply': 'das Netzteil',
    'the operating system': 'das Betriebssystem',
    'the application': 'die Anwendung',
    'the menu': 'das Menü',
    'the button': 'die Schaltfläche',
    'the window': 'das Fenster',
    'the tab': 'der Tab',
    'the setting': 'die Einstellung',
    'the notification': 'die Benachrichtigung',
    'the error': 'der Fehler',
    'the bug': 'der Programmfehler',
    'the solution': 'die Lösung',
    'the instruction': 'die Anleitung',
    'the manual': 'das Handbuch',
    'the installation': 'die Installation',
    'the version': 'die Version',
    'the access': 'der Zugang',
    'the permission': 'die Berechtigung',
    'the security': 'die Sicherheit',
    'the encryption': 'die Verschlüsselung',
    'the firewall': 'die Firewall',
    'the virus': 'der Virus',
    'the scanner': 'der Scanner',
    'the copy': 'die Kopie',
    'the document': 'das Dokument',
    'the spreadsheet': 'die Tabelle',
    'the presentation': 'die Präsentation',
    'the project': 'das Projekt',
    'the code': 'der Code',
    'the command': 'der Befehl',
    'the terminal': 'das Terminal',
    'the script': 'das Skript',
    'the tool': 'das Werkzeug',
    'the machine': 'die Maschine',
    'the robot': 'der Roboter',
    'the sensor': 'der Sensor',
    'the motor': 'der Motor',
    'the switch': 'der Schalter',
    'the signal': 'das Signal',
    'the antenna': 'die Antenne',
    'the satellite': 'der Satellit',
    'the remote control': 'die Fernbedienung',
    'the charger cable': 'das Ladekabel',
    'the extension cable': 'das Verlängerungskabel',
    'the power': 'der Strom',
    'the energy': 'die Energie',
    'the measurement': 'die Messung',
    'the device setting': 'die Geräteeinstellung',
    'the user account': 'das Benutzerkonto',
    'the data': 'die Daten',
    'the interface': 'die Schnittstelle'
}

df = pd.DataFrame.from_dict(
    words,
    orient="index",
    columns=["German"]
)

df.index.name = "English"

df.to_csv("../csv-files/dict_Nomen_Technik.csv")
