import pandas as pd

words = {
    'the clothing': 'die Kleidung',
    'the shirt': 'das Hemd',
    'the blouse': 'die Bluse',
    'the T-shirt': 'das T-Shirt',
    'the sweater': 'der Pullover',
    'the jacket': 'die Jacke',
    'the coat': 'der Mantel',
    'the trousers': 'die Hose',
    'the jeans': 'die Jeans',
    'the skirt': 'der Rock',
    'the dress': 'das Kleid',
    'the shoe': 'der Schuh',
    'the sock': 'die Socke',
    'the hat': 'der Hut',
    'the cap': 'die Mütze',
    'the scarf': 'der Schal',
    'the glove': 'der Handschuh',
    'the belt': 'der Gürtel',
    'the button': 'der Knopf',
    'the zipper': 'der Reißverschluss',
    'the suit': 'der Anzug',
    'the tie': 'die Krawatte',
    'the bow tie': 'die Fliege',
    'the vest': 'die Weste',
    'the hoodie': 'der Kapuzenpullover',
    'the sweatshirt': 'das Sweatshirt',
    'the cardigan': 'die Strickjacke',
    'the blazer': 'der Blazer',
    'the raincoat': 'der Regenmantel',
    'the winter coat': 'der Wintermantel',
    'the down jacket': 'die Daunenjacke',
    'the leather jacket': 'die Lederjacke',
    'the tracksuit': 'der Trainingsanzug',
    'the sportswear': 'die Sportkleidung',
    'the underwear': 'die Unterwäsche',
    'the undershirt': 'das Unterhemd',
    'the underpants': 'die Unterhose',
    'the bra': 'der BH',
    'the pajamas': 'der Schlafanzug',
    'the nightgown': 'das Nachthemd',
    'the bathrobe': 'der Bademantel',
    'the swimsuit': 'der Badeanzug',
    'the swimming trunks': 'die Badehose',
    'the bikini': 'der Bikini',
    'the tights': 'die Strumpfhose',
    'the stocking': 'der Strumpf',
    'the sneaker': 'der Turnschuh',
    'the boot': 'der Stiefel',
    'the sandal': 'die Sandale',
    'the slipper': 'der Hausschuh',
    'the high heel': 'der Absatzschuh',
    'the shoelace': 'der Schnürsenkel',
    'the sole': 'die Sohle',
    'the heel': 'der Absatz',
    'the pocket': 'die Tasche',
    'the sleeve': 'der Ärmel',
    'the collar': 'der Kragen',
    'the hood': 'die Kapuze',
    'the seam': 'die Naht',
    'the fabric': 'der Stoff',
    'the cotton': 'die Baumwolle',
    'the wool': 'die Wolle',
    'the silk': 'die Seide',
    'the leather': 'das Leder',
    'the denim': 'der Jeansstoff',
    'the size': 'die Größe',
    'the clothing size': 'die Kleidergröße',
    'the shoe size': 'die Schuhgröße',
    'the color': 'die Farbe',
    'the pattern': 'das Muster',
    'the stripe': 'der Streifen',
    'the dot': 'der Punkt',
    'the stain': 'der Fleck',
    'the laundry': 'die Wäsche',
    'the washing machine': 'die Waschmaschine',
    'the dryer': 'der Trockner',
    'the detergent': 'das Waschmittel',
    'the clothesline': 'die Wäscheleine',
    'the hanger': 'der Kleiderbügel',
    'the wardrobe': 'der Kleiderschrank',
    'the changing room': 'die Umkleidekabine',
    'the fitting': 'die Anprobe',
    'the outfit': 'das Outfit',
    'the fashion': 'die Mode',
    'the style': 'der Stil',
    'the trend': 'der Trend',
    'the jewelry': 'der Schmuck',
    'the ring': 'der Ring',
    'the necklace': 'die Halskette',
    'the bracelet': 'das Armband',
    'the earring': 'der Ohrring',
    'the watch': 'die Uhr',
    'the sunglasses': 'die Sonnenbrille',
    'the bag': 'die Handtasche',
    'the backpack': 'der Rucksack',
    'the wallet': 'der Geldbeutel',
    'the umbrella': 'der Regenschirm',
    'the uniform': 'die Uniform',
    'the work clothes': 'die Arbeitskleidung',
    'the apron': 'die Schürze'
}

df = pd.DataFrame.from_dict(
    words,
    orient="index",
    columns=["German"]
)

df.index.name = "English"

df.to_csv("../csv-files/dict_Nomen_Kleidung.csv")
