import pandas as pd

words = {
    "the application": "die Bewerbung",
    "the job advertisement": "die Stellenanzeige",
    "the position": "die Stelle",
    "the vacancy": "die freie Stelle",
    "the applicant": "der Bewerber",
    "the candidate": "der Kandidat",
    "the employer": "der Arbeitgeber",
    "the employee": "der Arbeitnehmer",
    "the company": "das Unternehmen",
    "the recruiter": "der Personalvermittler",
    "the human resources department": "die Personalabteilung",
    "the cover letter": "das Anschreiben",
    "the resume": "der Lebenslauf",
    "the curriculum vitae": "die Vita",
    "the certificate": "das Zeugnis",
    "the degree": "der Abschluss",
    "the qualification": "die Qualifikation",
    "the experience": "die Erfahrung",
    "the skill": "die Fähigkeit",
    "the strength": "die Stärke",
    "the weakness": "die Schwäche",
    "the reference": "die Referenz",
    "the portfolio": "das Portfolio",
    "the interview": "das Vorstellungsgespräch",
    "the appointment": "der Termin",
    "the invitation": "die Einladung",
    "the rejection": "die Absage",
    "the acceptance": "die Zusage",
    "the trial day": "der Probetag",
    "the probation period": "die Probezeit",
    "the employment contract": "der Arbeitsvertrag",
    "the salary expectation": "die Gehaltsvorstellung",
    "the notice period": "die Kündigungsfrist",
    "the start date": "der Eintrittstermin",
    "the signature": "die Unterschrift",
    "the application photo": "das Bewerbungsfoto",
    "the job portal": "das Jobportal",
    "the career": "die Karriere",
    "the internship": "das Praktikum",
    "the training": "die Ausbildung",
    "the apprenticeship": "die Lehre",
    "the university degree": "der Hochschulabschluss",
    "the school certificate": "das Schulzeugnis",
    "the diploma": "das Diplom",
    "the master degree": "der Masterabschluss",
    "the bachelor degree": "der Bachelorabschluss",
    "the work sample": "die Arbeitsprobe",
    "the recommendation": "die Empfehlung",
    "the motivation": "die Motivation",
    "the availability": "die Verfügbarkeit",
    "the relocation": "der Umzug",
    "the commute": "der Arbeitsweg",
    "the workplace": "der Arbeitsplatz",
    "the job title": "die Berufsbezeichnung",
    "the requirement": "die Anforderung",
    "the responsibility": "die Verantwortung",
    "the benefit": "die Zusatzleistung",
    "the pension plan": "die Altersvorsorge",
    "the vacation entitlement": "der Urlaubsanspruch",
    "the working hours": "die Arbeitszeit",
    "the part-time job": "die Teilzeitstelle",
    "the full-time job": "die Vollzeitstelle",
    "the temporary job": "die befristete Stelle",
    "the permanent job": "die Festanstellung",
    "the remote work": "die Fernarbeit",
    "the home office": "das Homeoffice",
    "the salary": "das Gehalt",
    "the wage": "der Lohn",
    "the bonus": "die Prämie",
    "the notice": "die Kündigung",
    "the trial work": "die Probearbeit",
    "the assessment center": "das Assessment-Center",
    "the phone interview": "das Telefoninterview",
    "the video interview": "das Videointerview",
    "the question": "die Frage",
    "the answer": "die Antwort",
    "the impression": "der Eindruck",
    "the appearance": "das Auftreten",
    "the clothing": "die Kleidung",
    "the punctuality": "die Pünktlichkeit",
    "the preparation": "die Vorbereitung",
    "the research": "die Recherche",
    "the address": "die Adresse",
    "the phone number": "die Telefonnummer",
    "the email address": "die E-Mail-Adresse",
    "the contact person": "der Ansprechpartner",
    "the salutation": "die Anrede",
    "the introduction": "die Einleitung",
    "the closing": "der Schluss",
    "the attachment": "der Anhang",
    "the PDF file": "die PDF-Datei",
    "the online form": "das Onlineformular",
    "the deadline": "die Bewerbungsfrist",
    "the confirmation": "die Bestätigung",
    "the feedback": "die Rückmeldung",
    "the selection": "die Auswahl",
    "the contract offer": "das Vertragsangebot",
    "the career change": "der Berufswechsel",
    "the dream job": "der Traumjob",
    "the portfolio website": "die Portfolioseite"
}

df = pd.DataFrame.from_dict(
    words,
    orient="index",
    columns=["German"]
)

df.index.name = "English"

df.to_csv("../csv-files/dict_Nomen_Bewerbung.csv")
