import pandas as pd

words = {
    "the city": "die Stadt",
    "the town": "die Kleinstadt",
    "the village": "das Dorf",
    "the street": "die Straße",
    "the square": "der Platz",
    "the intersection": "die Kreuzung",
    "the traffic light": "die Ampel",
    "the sidewalk": "der Gehweg",
    "the bridge": "die Brücke",
    "the station": "der Bahnhof",
    "the bus stop": "die Bushaltestelle",
    "the subway": "die U-Bahn",
    "the tram": "die Straßenbahn",
    "the train": "der Zug",
    "the bus": "der Bus",
    "the taxi": "das Taxi",
    "the car": "das Auto",
    "the bicycle": "das Fahrrad",
    "the parking lot": "der Parkplatz",
    "the park": "der Park",
    "the playground": "der Spielplatz",
    "the market": "der Markt",
    "the supermarket": "der Supermarkt",
    "the bakery": "die Bäckerei",
    "the pharmacy": "die Apotheke",
    "the hospital": "das Krankenhaus",
    "the doctor office": "die Arztpraxis",
    "the school": "die Schule",
    "the university": "die Universität",
    "the library": "die Bibliothek",
    "the museum": "das Museum",
    "the theater": "das Theater",
    "the cinema": "das Kino",
    "the restaurant": "das Restaurant",
    "the café": "das Café",
    "the hotel": "das Hotel",
    "the bank": "die Bank",
    "the post office": "die Post",
    "the police station": "die Polizeiwache",
    "the city hall": "das Rathaus",
    "the fire station": "die Feuerwache",
    "the courthouse": "das Gericht",
    "the prison": "das Gefängnis",
    "the church": "die Kirche",
    "the mosque": "die Moschee",
    "the synagogue": "die Synagoge",
    "the cemetery": "der Friedhof",
    "the shopping center": "das Einkaufszentrum",
    "the shop": "das Geschäft",
    "the bookstore": "die Buchhandlung",
    "the butcher shop": "die Metzgerei",
    "the hairdresser": "der Friseur",
    "the kiosk": "der Kiosk",
    "the gas station": "die Tankstelle",
    "the workshop": "die Werkstatt",
    "the factory": "die Fabrik",
    "the office building": "das Bürogebäude",
    "the apartment building": "das Wohnhaus",
    "the skyscraper": "das Hochhaus",
    "the neighborhood": "das Viertel",
    "the district": "der Bezirk",
    "the suburb": "der Vorort",
    "the center": "das Zentrum",
    "the old town": "die Altstadt",
    "the pedestrian zone": "die Fußgängerzone",
    "the avenue": "die Allee",
    "the alley": "die Gasse",
    "the corner": "die Ecke",
    "the sign": "das Schild",
    "the streetlight": "die Straßenlaterne",
    "the bench": "die Sitzbank",
    "the fountain": "der Brunnen",
    "the monument": "das Denkmal",
    "the statue": "die Statue",
    "the river": "der Fluss",
    "the harbor": "der Hafen",
    "the canal": "der Kanal",
    "the tunnel": "der Tunnel",
    "the overpass": "die Überführung",
    "the underpass": "die Unterführung",
    "the crosswalk": "der Zebrastreifen",
    "the bike lane": "der Radweg",
    "the bus lane": "die Busspur",
    "the platform": "der Bahnsteig",
    "the timetable": "der Fahrplan",
    "the ticket machine": "der Fahrkartenautomat",
    "the ticket": "die Fahrkarte",
    "the stop": "die Haltestelle",
    "the airport": "der Flughafen",
    "the hostel": "die Jugendherberge",
    "the guesthouse": "die Pension",
    "the playground equipment": "das Spielgerät",
    "the public toilet": "die öffentliche Toilette",
    "the recycling container": "der Altglascontainer",
    "the trash can": "der Mülleimer",
    "the construction site": "die Baustelle",
    "the crane": "der Kran",
    "the map": "der Stadtplan",
    "the information desk": "die Information",
    "the town hall square": "der Rathausplatz"
}

df = pd.DataFrame.from_dict(
    words,
    orient="index",
    columns=["German"]
)

df.index.name = "English"

df.to_csv("../csv-files/dict_Nomen_Stadt.csv")
